number1 = input("Enter number:")
number2 = input("Enter number:")
number3 = input("Enter number:")
number4 = input("Enter number:")
number5 = input("Enter number:")

sum = int(number1) +int(number2) +int(number3) +int(number4) + int(number5)
print(sum)
print("The average of those numbers is")
print(sum/5)
